- hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Include OS-specific variables. 
      include_vars: "{{ playbook_dir }}/defaults/main.yml" 

    - import_tasks: "{{ playbook_dir }}/tasks/main.yml"
