---
- name: Converge
  hosts: all
  gather_facts: true
  tasks: 
#    - name: Replace this task with one that validates your content
#      ansible.builtin.debug:
#        msg: "This is the effective test"
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
    - name: Update apt cache (on Debian)
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - import_tasks: ../../tasks/main.yml
